### PR TITLE
fix unusual behaviour on deselecting an icon

### LINKED ISSUE #82: Unusual behaviour on deselecting an icon
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When we click on an already selected icon to deselect it. It takes double clicks to deselect it. Upon deselecting the icon, URL and search params remain populated with the data of the last selected icon. 

### Expected Behavior

Deselecting an icon in a single click, and clearing out the URL and search params upon deselecting.

### Steps To Reproduce

1. Open the site and select any icon.
2. Try to deselect it ( It will take more than one clicks)
3. Once unselected visit the search and URL; they still remain populated.

### Anything else?

_No response_

### What browsers are you seeing the problem on?

_No response_

### PR DESCRIPTION
**Pull request by ayushsatyam146**
Fixes #82. Earlier, for deselecting an icon it took double clicks and the search and URL params didn't get cleared. A video is attached below to show the current behavior after fixing the issue.

https://user-images.githubusercontent.com/55888723/157908533-26efc1a1-3925-4b6a-a614-aa26704a2f67.mp4

### CODE REVIEW

File: src/modules/IconsSet.js [hunk 1]
```diff
@@ -239,6 +239,7 @@ const IconsSet = (props) => {
   const selectIcon = (icon, callback) => {
     setShowPanel(icon !== iconSelected)
     setIconSelected(icon === iconSelected ? '' : icon)
+    setSearchValue(icon.name === searchValue ? '' : icon.name)
```
Comment (Abhirup-99) [inline src/modules/IconsSet.js:242]: can we change this to `setSearchValue(searchValue => icon.name === searchValue ? '' : icon.name)`? The current implementation would cause a bug with there are 2 very quick clicks, and React would batch the updates together.

Comment (ayushsatyam146) [reply src/modules/IconsSet.js]: Hi, I have implemented the changes you have asked for here. Please review.

**Comment by Abhirup-99** [comment]
> @ayushsatyam146 The functionality is not working for animated icons, It will be great if you can implement the same feature for animated icons.
> 

Preferable in a separate PR :). Smaller PRs rather than clubbing in a separate PR.

**Comment by ayushsatyam146** [comment]
@Abhirup-99 @vinayaksh42 I am opening an issue for the functionality of the animated icons and will make a separate PR for that. If everything is good with this PR can you please merge it?
